"use client";
import {useEffect,useMemo,useState} from "react"; import { useTeacherClass } from "../components/TeacherClassContext"; import {Music2, Users, Mic2, MessageCircle, CalendarDays, ExternalLink, Disc3} from "lucide-react";
type Song={id:string;studente_id:string;student_name:string;classe:string;titolo:string;artista:string;youtube_url:string;motivo:string;created_at:string;anno?:number|null};
export default function Dashboard(){const { selectedClass } = useTeacherClass(); const[songs,setSongs]=useState<Song[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{if(!selectedClass){setSongs([]);setLoading(false);return;} setLoading(true);fetch(`/api/class/songs?classe=${encodeURIComponent(selectedClass)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{setSongs(d.songs||[]);setLoading(false)})},[selectedClass]);const names=useMemo(()=>new Set(songs.map(s=>s.student_name)),[songs]);const artists=useMemo(()=>new Set(songs.map(s=>(s.artista ?? "").trim().toLowerCase())).size,[songs]);const artistCounts=useMemo(()=>Object.entries(songs.reduce((a,s)=>{const k=(s.artista ?? "").trim();a[k]=(a[k]||0)+1;return a},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]),[songs]);const latest=songs.slice(0,8);return <>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Users/>} value={names.size} label="studenti"/><Stat icon={<Music2/>} value={songs.length} label="brani raccolti"/><Stat icon={<Mic2/>} value={artists} label="artisti"/><Stat icon={<MessageCircle/>} value={songs.length} label="storie raccontate"/></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]">
  <section className="glass p-6 md:p-7"><div className="flex items-center justify-between"><div><div className="eyebrow">Ultimi ingressi</div><h2 className="mt-2 text-2xl font-bold">La playlist prende forma</h2><div className="mt-1 text-xs text-cyan-200/70">{selectedClass}</div></div><Disc3 className="text-violet-300"/></div>{loading?<p className="mt-8 muted">Caricamento…</p>:songs.length===0?<div className="mt-8 rounded-2xl bg-white/[.04] p-6 muted">Non ci sono ancora brani.</div>:<div className="mt-7 grid gap-3 sm:grid-cols-2">{latest.map((s,i)=><div key={s.id} className="music-card p-4"><div className="flex gap-4"><div className="cover flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl"><Music2 size={21} className="relative z-10"/></div><div className="min-w-0"><div className="truncate font-semibold">{s.titolo}</div><div className="truncate text-sm muted">{s.artista}</div><div className="mt-2 text-xs text-violet-200">{s.student_name}</div></div></div><a href={s.youtube_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs text-cyan-300">Ascolta su YouTube <ExternalLink size={11}/></a></div>)}</div>}</section>
  <section className="glass p-6 md:p-7"><div className="eyebrow">Top artisti</div><h2 className="mt-2 text-2xl font-bold">Chi ritorna più spesso</h2>{songs.length?<div className="mt-7 space-y-5">{artistCounts.slice(0,8).map(([a,n],i)=><div key={a}><div className="flex justify-between gap-4 text-sm"><span className="truncate"><span className="mr-2 text-xs text-violet-300">0{i+1}</span>{a}</span><span className="text-[#bfc0cd]">{n}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/7"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" style={{width:`${Math.max(7,Math.min(100,n/songs.length*100))}%`}}/></div></div>)}</div>:<p className="mt-7 muted">Nessun dato.</p>}</section>
 </div>
 <section className="glass mt-6 p-6 md:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-pink-400/10 text-pink-300"><MessageCircle size={19}/></div><div><div className="eyebrow">Le storie dietro la musica</div><h2 className="mt-1 text-2xl font-bold">Motivazioni</h2></div></div><div className="mt-6 grid gap-4 md:grid-cols-2">{songs.slice(0,6).map(s=><blockquote key={s.id} className="rounded-2xl bg-white/[.035] p-5"><p className="leading-7 text-[#d7d7e1]">“{s.motivo}”</p><footer className="mt-4 text-xs font-semibold text-violet-200">— {s.student_name} · {s.titolo}</footer></blockquote>)}</div></section>
 </>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className="glass p-5"><div className="flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/6 text-violet-300">{icon}</div><CalendarDays size={15} className="text-[#66697c]"/></div><div className="mt-6 stat-number">{value}</div><div className="mt-2 text-sm muted">{label}</div></div>}
