 "use client";
import {useEffect,useMemo,useState} from "react"; import Link from "next/link";
type Song={id:string;student_name:string;title:string;artist:string;youtube_url:string;reason:string;created_at:string;year?:number|null};
export default function Dashboard(){const [songs,setSongs]=useState<Song[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/songs").then(r=>r.json()).then(d=>{setSongs(d.songs||[]);setLoading(false)})},[]);
 const artists=useMemo(()=>new Set(songs.map(s=>s.artist.toLowerCase())).size,[songs]); const years=songs.map(s=>(s as any).year).filter((y:number|undefined): y is number => Boolean(y)); const names=new Set(songs.map(s=>s.student_name));
 const artistCounts=Object.entries(songs.reduce((a,s)=>{a[s.artist]=(a[s.artist]||0)+1;return a},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]);
 return <main className="min-h-screen px-5 py-8 md:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[.2em] text-neutral-500">Area docente</p><h1 className="mt-2 text-4xl font-semibold">La classe in numeri</h1></div><div className="flex gap-2"><Link href="/docente/mappa" className="rounded-xl border border-neutral-200 bg-white px-4 py-2 text-sm">🕸️ Mappa</Link><Link href="/docente/indovina" className="rounded-xl bg-black px-4 py-2 text-sm text-white">🕵️ Indovina</Link></div></div>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["👥",names.size,"studenti"],["🎵",songs.length,"canzoni"],["🎤",artists,"artisti"],["💬",songs.length,"motivazioni"],["📅",years.length?`${Math.min(...years)}–${Math.max(...years)}`:"—","anni"]].map(x=><div className="card p-5" key={String(x[2])}><div className="text-xl">{x[0]}</div><div className="mt-4 text-3xl font-semibold">{x[1]}</div><div className="text-sm text-neutral-500">{x[2]}</div></div>)}</div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="card p-6"><h2 className="text-xl font-semibold">🎵 Canzoni della classe</h2>{loading?<p className="mt-6 text-neutral-500">Caricamento…</p>:songs.length===0?<p className="mt-6 text-neutral-500">Non ci sono ancora canzoni.</p>:<div className="mt-5 space-y-2">{songs.map((s,i)=><div key={s.id} className="flex items-center justify-between gap-4 rounded-xl bg-neutral-50 p-4"><div className="min-w-0"><div className="font-medium">{i+1}. {s.title}</div><div className="text-sm text-neutral-500">{s.artist} · {s.student_name}</div></div><a target="_blank" href={s.youtube_url} className="shrink-0 text-sm underline">YouTube</a></div>)}</div>}</section>
 <section className="card p-6"><h2 className="text-xl font-semibold">🎤 Artisti più presenti</h2><div className="mt-5 space-y-3">{artistCounts.slice(0,8).map(([a,n],i)=><div key={a}><div className="flex justify-between text-sm"><span>{i+1}. {a}</span><span>{n}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-neutral-100"><div className="h-full rounded-full bg-black" style={{width:`${Math.min(100,n/songs.length*100)}%`}}/></div></div>)}</div></section></div>
 <div className="mt-6 card p-6"><h2 className="text-xl font-semibold">❤️ Motivazioni</h2><p className="mt-2 text-neutral-500">Qui verrà aggiunta l’analisi automatica dei temi ricorrenti e delle parole chiave. Per ora le motivazioni sono conservate integralmente nel database.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{songs.slice(0,6).map(s=><blockquote key={s.id} className="rounded-xl bg-neutral-50 p-4 text-sm text-neutral-600">“{s.reason}”<footer className="mt-2 font-medium text-neutral-900">— {s.student_name}</footer></blockquote>)}</div></div></div></main>
}