"use client";
import { useEffect, useState } from "react";

type Student={id:string;nome:string;codice_personale:string;classe:string;attivo:boolean;canzoni?:{id:string;titolo:string}[]};

export default function GestioneClasse(){
 const [students,setStudents]=useState<Student[]>([]),[classe,setClasse]=useState(""),[nomi,setNomi]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);
 async function load(){setLoading(true);const r=await fetch('/api/class/students',{cache:'no-store'});const d=await r.json();if(r.ok)setStudents(d.students||[]);else setError(d.error||'Errore');setLoading(false)}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");setDone(false);const r=await fetch('/api/class/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classe,nomi})});const d=await r.json();if(!r.ok)setError(d.error||'Errore');else{setDone(true);setNomi("");await load()}setSaving(false)}
 function print(){window.print()}
 return <div className="mt-10 grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
  <section className="card p-6 print:hidden"><p className="text-sm uppercase tracking-[.2em] text-neutral-500">Nuova classe</p><h2 className="mt-2 text-2xl font-semibold">Aggiungi studenti</h2><p className="mt-2 text-sm leading-6 text-neutral-500">Inserisci un nome per riga. Il sistema assegnerà automaticamente un codice personale.</p>
   <form onSubmit={add} className="mt-6 space-y-4"><label className="block text-sm font-medium">Classe<input value={classe} onChange={e=>setClasse(e.target.value)} placeholder="Es. 5AINT" className="mt-2 w-full rounded-xl border border-neutral-200 px-4 py-3" required/></label><label className="block text-sm font-medium">Elenco studenti<textarea value={nomi} onChange={e=>setNomi(e.target.value)} placeholder={'Mario Rossi\nGiulia Bianchi\nLuca Verdi'} rows={9} className="mt-2 w-full rounded-xl border border-neutral-200 px-4 py-3" required/></label>{error&&<p className="text-sm text-red-600">{error}</p>}{done&&<p className="text-sm text-green-700">Studenti aggiunti e codici generati.</p>}<button disabled={saving} className="w-full rounded-xl bg-black px-5 py-3.5 text-white">{saving?'Salvataggio…':'Genera codici e aggiungi'}</button></form>
  </section>
  <section className="card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm uppercase tracking-[.2em] text-neutral-500">Elenco classe</p><h2 className="mt-2 text-2xl font-semibold">Codici personali</h2></div><button onClick={print} className="rounded-xl border border-neutral-200 px-4 py-2 text-sm print:hidden">🖨️ Stampa</button></div>{loading?<p className="mt-6 text-neutral-500">Caricamento…</p>:students.length===0?<p className="mt-6 text-neutral-500">Non ci sono ancora studenti.</p>:<div className="mt-6 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-neutral-500"><th className="px-3 py-3">Studente</th><th className="px-3 py-3">Classe</th><th className="px-3 py-3">Codice</th><th className="px-3 py-3">Canzone</th></tr></thead><tbody>{students.map(s=><tr key={s.id} className="border-b last:border-0"><td className="px-3 py-3 font-medium">{s.nome}</td><td className="px-3 py-3">{s.classe}</td><td className="px-3 py-3 font-mono font-semibold tracking-wider">{s.codice_personale}</td><td className="px-3 py-3">{s.canzoni?.[0]?.titolo?<span className="text-green-700">✓ {s.canzoni[0].titolo}</span>:<span className="text-neutral-400">Non ancora</span>}</td></tr>)}</tbody></table></div>}</section>
 </div>
}
