import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase non configurato");return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}})}
function normalize(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function youtube(v:string){try{return ["youtube.com","www.youtube.com","youtu.be","m.youtube.com"].includes(new URL(v).hostname.toLowerCase())}catch{return false}}
type Incoming={id?:unknown;titolo?:unknown;artista?:unknown;youtube_url?:unknown;motivo?:unknown};
export async function POST(req:Request){try{const body=await req.json();const codice=String(body?.codice??"").trim().toUpperCase();const incoming:Incoming[]=Array.isArray(body?.songs)?body.songs:[];if(!codice)return NextResponse.json({error:"Codice personale non riconosciuto."},{status:400});if(incoming.length<5||incoming.length>10)return NextResponse.json({error:"La playlist deve contenere da 5 a 10 canzoni."},{status:400});const songs=incoming.map(s=>({id:s.id?String(s.id):undefined,titolo:String(s.titolo??"").trim(),artista:String(s.artista??"").trim(),youtube_url:String(s.youtube_url??"").trim(),motivo:String(s.motivo??"").trim()}));for(const s of songs){if(!s.titolo||!s.artista||!s.youtube_url||!s.motivo)return NextResponse.json({error:"Compila tutti i campi delle canzoni."},{status:400});if(!youtube(s.youtube_url))return NextResponse.json({error:`Il link di “${s.titolo}” non è un link valido a YouTube.`},{status:400});if(s.motivo.length<10)return NextResponse.json({error:`Racconta un po' meglio perché hai scelto “${s.titolo}”.`},{status:400})}
 const sb=db();const {data:student,error:se}=await sb.from("studenti").select("id,nome,classe,attivo").eq("codice_personale",codice).maybeSingle();if(se)throw se;if(!student||!student.attivo)return NextResponse.json({error:"Codice personale non riconosciuto."},{status:404});
 const keys=new Set<string>();for(const s of songs){const k=`${normalize(s.titolo)}|${normalize(s.artista)}`;if(keys.has(k))return NextResponse.json({error:`La canzone “${s.titolo}” è presente più di una volta.`},{status:409});keys.add(k)}
 const {data:existing,error:ee}=await sb.from("canzoni").select("id").eq("studente_id",student.id);if(ee)throw ee;const ids=new Set((existing??[]).map(x=>String(x.id)));for(const s of songs.filter(x=>x.id)){if(!ids.has(s.id!))return NextResponse.json({error:"Una delle canzoni selezionate non appartiene alla tua playlist."},{status:403})}
 const keep=new Set(songs.filter(s=>s.id).map(s=>s.id!));const remove=(existing??[]).filter(x=>!keep.has(String(x.id))).map(x=>x.id);if(remove.length){const {error}=await sb.from("canzoni").delete().in("id",remove).eq("studente_id",student.id);if(error)throw error}
 for(const s of songs.filter(x=>x.id)){const {error}=await sb.from("canzoni").update({titolo:s.titolo,artista:s.artista,youtube_url:s.youtube_url,motivo:s.motivo,titolo_normalizzato:normalize(s.titolo)}).eq("id",s.id!).eq("studente_id",student.id);if(error)throw error}
 const fresh=songs.filter(s=>!s.id).map(s=>({studente_id:student.id,titolo:s.titolo,artista:s.artista,youtube_url:s.youtube_url,motivo:s.motivo,titolo_normalizzato:normalize(s.titolo)}));if(fresh.length){const {error}=await sb.from("canzoni").insert(fresh);if(error)throw error}
 const {data:final,error:fe}=await sb.from("canzoni").select("id,titolo,artista,youtube_url,motivo").eq("studente_id",student.id).order("created_at",{ascending:true});if(fe)throw fe;return NextResponse.json({ok:true,total:final?.length??0,songs:final??[],student:{nome:student.nome,classe:student.classe}});
 }catch(error){console.error(error);return NextResponse.json({error:"Non è stato possibile salvare la playlist."},{status:500})}}
